In [120]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

## Reading dataset from google drive and saving it as df

In [123]:
path = '/content/drive/MyDrive/DeepTech/Week-2/1.3 Business Funding Data.csv'
df = pd.read_csv(path, encoding='latin-1') # Changed encoding to 'latin-1'
df.head(5)

Website Domain Effective date                   Found At Financing Type  \
0  trafigura.com            NaN  2024-03-14T01:00:00+01:00            NaN   
1     zenobe.com            NaN  2024-05-31T02:00:00+02:00            NaN   
2     zenobe.com            NaN  2024-07-24T02:00:00+02:00            NaN   
3      canva.com            NaN  2024-05-01T02:00:00+02:00            NaN   
4   fidelity.com            NaN  2024-04-11T02:00:00+02:00            NaN   

  Financing Type Normalized          Categories  \
0                       NaN                  []   
1                       NaN                  []   
2                       NaN  ["private_equity"]   
3                       NaN                  []   
4                       NaN                  []   

                                           Investors  Investors Count  \
0                                                NaN              NaN   
1  avivainvestors.com, lloydsbankinggroup.com, sa...              9.0   
2                                                NaN              NaN   
3                              stackcapitalgroup.com              1.0   
4                                chevychasetrust.com              1.0   

           Amount  Amount Normalized  \
0           $1.9b         1900000000   
1  $522.7 million          522700000   
2          £41.7m           53671000   
3    US$8 million            8000000   
4   $1.96 million            1960000   

                                         Source Urls  
0  https://www.tradefinanceglobal.com/posts/trafi...  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Website Domain             26 non-null     object 
 1   Effective date             6 non-null      object 
 2   Found At                   26 non-null     object 
 3   Financing Type             8 non-null      object 
 4   Financing Type Normalized  8 non-null      object 
 5   Categories                 26 non-null     object 
 6   Investors                  13 non-null     object 
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object 
 9   Amount Normalized          26 non-null     int64  
 10  Source Urls                26 non-null     object 
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB


## Display the percentage of missing values in each column

In [125]:
# Missing Values
Missing_percentage = df.isnull().sum() / len(df) * 100
print(Missing_percentage)

Website Domain                0.000000
Effective date               76.923077
Found At                      0.000000
Financing Type               69.230769
Financing Type Normalized    69.230769
Categories                    0.000000
Investors                    50.000000
Investors Count              50.000000
Amount                        0.000000
Amount Normalized             0.000000
Source Urls                   0.000000
dtype: float64


## To see how many unique values we have in the 'Effective date' column which has the highest number of missing values

In [126]:
df['Effective date'].unique()

array([nan, '2024-04-18T02:00:00+02:00', '2024-04-16T02:00:00+02:00',
       '2024-06-20T02:00:00+02:00', '2024-04-24T02:00:00+02:00',
       '2024-06-26T02:00:00+02:00', '2024-06-27T02:00:00+02:00'],
      dtype=object)

## Since the values in the 'Effective date' column are not really consistent and can't be used to infer other values in the table, it's a better choice to drop it.

In [127]:
df.drop(columns=['Effective date'], inplace=True)
df.head(5)

Website Domain                   Found At Financing Type  \
0  trafigura.com  2024-03-14T01:00:00+01:00            NaN   
1     zenobe.com  2024-05-31T02:00:00+02:00            NaN   
2     zenobe.com  2024-07-24T02:00:00+02:00            NaN   
3      canva.com  2024-05-01T02:00:00+02:00            NaN   
4   fidelity.com  2024-04-11T02:00:00+02:00            NaN   

  Financing Type Normalized          Categories  \
0                       NaN                  []   
1                       NaN                  []   
2                       NaN  ["private_equity"]   
3                       NaN                  []   
4                       NaN                  []   

                                           Investors  Investors Count  \
0                                                NaN              NaN   
1  avivainvestors.com, lloydsbankinggroup.com, sa...              9.0   
2                                                NaN              NaN   
3                              stackcapitalgroup.com              1.0   
4                                chevychasetrust.com              1.0   

           Amount  Amount Normalized  \
0           $1.9b         1900000000   
1  $522.7 million          522700000   
2          £41.7m           53671000   
3    US$8 million            8000000   
4   $1.96 million            1960000   

                                         Source Urls  
0  https://www.tradefinanceglobal.com/posts/trafi...  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...

## Checking the uniqueness of the 'Financing Type' and 'Financing Type Normalized' column which also has 69% of missing values each

In [128]:
df['Financing Type'].unique()

array([nan, 'Series B', 'Series I', 'Seed', 'Series A2', 'Series A'],
      dtype=object)

In [129]:
df['Financing Type Normalized'].unique()

array([nan, 'series_b', 'series_i', 'seed', 'series_a2', 'series_a'],
      dtype=object)

## After discovering that the 'Category' column is covering the property of the 'Financing Type' column with more details, and that the 'Financial Type Normalized' column is a duplicate of the 'Financial Type' column, I decided to drop the 'Financial Type' & 'Financial Type Normalized' Column because they're no longer relevant

In [130]:
df.drop(columns=['Financing Type'], inplace=True)
df.drop(columns=['Financing Type Normalized'], inplace=True)
df.head(5)

Website Domain                   Found At          Categories  \
0  trafigura.com  2024-03-14T01:00:00+01:00                  []   
1     zenobe.com  2024-05-31T02:00:00+02:00                  []   
2     zenobe.com  2024-07-24T02:00:00+02:00  ["private_equity"]   
3      canva.com  2024-05-01T02:00:00+02:00                  []   
4   fidelity.com  2024-04-11T02:00:00+02:00                  []   

                                           Investors  Investors Count  \
0                                                NaN              NaN   
1  avivainvestors.com, lloydsbankinggroup.com, sa...              9.0   
2                                                NaN              NaN   
3                              stackcapitalgroup.com              1.0   
4                                chevychasetrust.com              1.0   

           Amount  Amount Normalized  \
0           $1.9b         1900000000   
1  $522.7 million          522700000   
2          £41.7m           53671000   
3    US$8 million            8000000   
4   $1.96 million            1960000   

                                         Source Urls  
0  https://www.tradefinanceglobal.com/posts/trafi...  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...

## Checking the uniqueness of the 'Categories' column

In [131]:
df['Categories'].unique()

array(['[]', '["private_equity"]', '["series_b", "venture"]',
       '["debt_financing"]', '["series_i", "venture"]',
       '["seed", "venture"]', '["series_a2", "venture"]',
       '["series_a", "venture"]', '["private_equity", "venture"]'],
      dtype=object)

## Since the Categories Column has more relevant data but also has empty list as the mode, I will write a python script to replace the mode with 'private_equity' which is the next unique mode

In [132]:
# check for rows in the categories column having empty list as value and replace with 'private_equirt'
for index, row in df.iterrows():
  if row['Categories'] == '[]':
    df.at[index, 'Categories'] = '["private_equity"]'

# Remove the brackets and double quotes from the Categories column to make it clean
df['Categories'] = df['Categories'].str.replace('[', '').str.replace(']', '').str.replace('"', '')

## Checking the uniqueness of the 'Investors' column and the 'Investors count' column

In [133]:
df['Investors'].unique()

array([nan,
       'avivainvestors.com, lloydsbankinggroup.com, santander.co.uk, swip.com, cibc.com, societegenerale.com, natwest.us, rabobank.com, mufg.jp',
       'stackcapitalgroup.com', 'chevychasetrust.com',
       'alantra.com, blueearth.capital', 'runwaygrowth.com',
       'damachotelsandresorts.com', 'surocap.com', 'eib.org',
       'vistaragrowth.com', 'accelia.vc',
       'edc.ca, desjardinscapital.com, fondsftq.com', 'cibc.com',
       'inovia.vc'], dtype=object)

In [134]:
df['Investors Count'].unique()

array([nan,  9.,  1.,  2.,  3.])

## Find the mode of the 'Investors' column, and the median of the 'Investors Count' column and fill the empty rolls with the mode and mode respectively

In [135]:
investors_mode = df['Investors'].mode()[0]
investors_median = df['Investors Count'].median()

# Fill NaN values in the 'Investors' column with the mode
df['Investors'].fillna(investors_mode, inplace=True)

# Fill NaN values in the 'Investors Count' column with the median
df['Investors Count'].fillna(investors_median, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Website Domain     26 non-null     object 
 1   Found At           26 non-null     object 
 2   Categories         26 non-null     object 
 3   Investors          26 non-null     object 
 4   Investors Count    26 non-null     float64
 5   Amount             26 non-null     object 
 6   Amount Normalized  26 non-null     int64  
 7   Source Urls        26 non-null     object 
dtypes: float64(1), int64(1), object(6)
memory usage: 1.8+ KB


<ipython-input-135-5126c48c6da4>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Investors'].fillna(investors_mode, inplace=True)
<ipython-input-135-5126c48c6da4>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', tr

## Confirming that our dataset is now ready to be used

In [136]:
df

Website Domain                   Found At               Categories  \
0         trafigura.com  2024-03-14T01:00:00+01:00           private_equity   
1            zenobe.com  2024-05-31T02:00:00+02:00           private_equity   
2            zenobe.com  2024-07-24T02:00:00+02:00           private_equity   
3             canva.com  2024-05-01T02:00:00+02:00           private_equity   
4          fidelity.com  2024-04-11T02:00:00+02:00           private_equity   
5       swtchenergy.com  2024-04-24T02:00:00+02:00        series_b, venture   
6            carnow.com  2024-04-16T02:00:00+02:00           debt_financing   
7        databricks.com  2024-08-07T02:00:00+02:00        series_i, venture   
8         anthropic.com  2024-07-08T02:00:00+02:00           private_equity   
9                ey.com  2024-04-18T02:00:00+02:00           private_equity   
10          openpipe.ai  2024-03-26T01:00:00+01:00            seed, venture   
11            canva.com  2024-05-09T02:00:00+02:00           private_equity   
12         syntetica.co  2024-07-16T02:00:00+02:00            seed, venture   
13               zf.com  2024-07-15T02:00:00+02:00           private_equity   
14        sparelabs.com  2024-06-05T02:00:00+02:00           private_equity   
15            e-zinc.ca  2024-06-27T02:00:00+02:00       series_a2, venture   
16  biointelligence.com  2024-04-25T02:00:00+02:00           private_equity   
17  claritisoftware.com  2024-04-10T02:00:00+02:00           private_equity   
18          heylist.com  2024-06-18T02:00:00+02:00           private_equity   
19           qohash.com  2024-04-24T02:00:00+02:00           private_equity   
20        topicflow.com  2024-06-25T02:00:00+02:00            seed, venture   
21  claritisoftware.com  2024-06-26T02:00:00+02:00           private_equity   
22  biointelligence.com  2024-04-30T02:00:00+02:00            seed, venture   
23            gaiia.com  2024-06-27T02:00:00+02:00        series_a, venture   
24       sinnstudio.com  2024-05-22T02:00:00+02:00  private_equity, venture   
25        topicflow.com  2024-06-25T02:00:00+02:00           private_equity   

                                            Investors  Investors Count  \
0                                          accelia.vc              1.0   
1   avivainvestors.com, lloydsbankinggroup.com, sa...              9.0   
2                                          accelia.vc              1.0   
3                               stackcapitalgroup.com              1.0   
4                                 chevychasetrust.com              1.0   
5                      alantra.com, blueearth.capital              2.0   
6                                    runwaygrowth.com              1.0   
7                                          accelia.vc              1.0   
8                           damachotelsandresorts.com              1.0   
9                                          accelia.vc              1.0   
10                                         accelia.vc              1.0   
11                                        surocap.com              1.0   
12                                         accelia.vc              1.0   
13                                            eib.org              1.0   
14                                         accelia.vc              1.0   
15                                         accelia.vc              1.0   
16                                         accelia.vc              1.0   
17                                  vistaragrowth.com              1.0   
18                                         accelia.vc              1.0   
19        edc.ca, desjardinscapital.com, fondsftq.com              3.0   
20                                         accelia.vc              1.0   
21                                           cibc.com              1.0   
22                                         accelia.vc              1.0   
23                                          inovia.vc              1.0   
24                       

## Drop the 'Amount' comlumn since it has been normalize

In [137]:
df.drop(columns=['Amount'], inplace=True)
df

Website Domain                   Found At               Categories  \
0         trafigura.com  2024-03-14T01:00:00+01:00           private_equity   
1            zenobe.com  2024-05-31T02:00:00+02:00           private_equity   
2            zenobe.com  2024-07-24T02:00:00+02:00           private_equity   
3             canva.com  2024-05-01T02:00:00+02:00           private_equity   
4          fidelity.com  2024-04-11T02:00:00+02:00           private_equity   
5       swtchenergy.com  2024-04-24T02:00:00+02:00        series_b, venture   
6            carnow.com  2024-04-16T02:00:00+02:00           debt_financing   
7        databricks.com  2024-08-07T02:00:00+02:00        series_i, venture   
8         anthropic.com  2024-07-08T02:00:00+02:00           private_equity   
9                ey.com  2024-04-18T02:00:00+02:00           private_equity   
10          openpipe.ai  2024-03-26T01:00:00+01:00            seed, venture   
11            canva.com  2024-05-09T02:00:00+02:00           private_equity   
12         syntetica.co  2024-07-16T02:00:00+02:00            seed, venture   
13               zf.com  2024-07-15T02:00:00+02:00           private_equity   
14        sparelabs.com  2024-06-05T02:00:00+02:00           private_equity   
15            e-zinc.ca  2024-06-27T02:00:00+02:00       series_a2, venture   
16  biointelligence.com  2024-04-25T02:00:00+02:00           private_equity   
17  claritisoftware.com  2024-04-10T02:00:00+02:00           private_equity   
18          heylist.com  2024-06-18T02:00:00+02:00           private_equity   
19           qohash.com  2024-04-24T02:00:00+02:00           private_equity   
20        topicflow.com  2024-06-25T02:00:00+02:00            seed, venture   
21  claritisoftware.com  2024-06-26T02:00:00+02:00           private_equity   
22  biointelligence.com  2024-04-30T02:00:00+02:00            seed, venture   
23            gaiia.com  2024-06-27T02:00:00+02:00        series_a, venture   
24       sinnstudio.com  2024-05-22T02:00:00+02:00  private_equity, venture   
25        topicflow.com  2024-06-25T02:00:00+02:00           private_equity   

                                            Investors  Investors Count  \
0                                          accelia.vc              1.0   
1   avivainvestors.com, lloydsbankinggroup.com, sa...              9.0   
2                                          accelia.vc              1.0   
3                               stackcapitalgroup.com              1.0   
4                                 chevychasetrust.com              1.0   
5                      alantra.com, blueearth.capital              2.0   
6                                    runwaygrowth.com              1.0   
7                                          accelia.vc              1.0   
8                           damachotelsandresorts.com              1.0   
9                                          accelia.vc              1.0   
10                                         accelia.vc              1.0   
11                                        surocap.com              1.0   
12                                         accelia.vc              1.0   
13                                            eib.org              1.0   
14                                         accelia.vc              1.0   
15                                         accelia.vc              1.0   
16                                         accelia.vc              1.0   
17                                  vistaragrowth.com              1.0   
18                                         accelia.vc              1.0   
19        edc.ca, desjardinscapital.com, fondsftq.com              3.0   
20                                         accelia.vc              1.0   
21                                           cibc.com              1.0   
22                                         accelia.vc              1.0   
23                                          inovia.vc              1.0   
24                       

## Checking for outliers

In [138]:
def remove_outliers_manual(df, column):
    mean = df[column].mean()
    std_dev = df[column].std()
    z_scores = np.abs((df[column] - mean) / std_dev)
    df_out = df[z_scores < 3]
    return df_out

In [139]:
remove_outliers_manual(df, 'Amount Normalized')
remove_outliers_manual(df, 'Investors Count')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Website Domain     26 non-null     object 
 1   Found At           26 non-null     object 
 2   Categories         26 non-null     object 
 3   Investors          26 non-null     object 
 4   Investors Count    26 non-null     float64
 5   Amount Normalized  26 non-null     int64  
 6   Source Urls        26 non-null     object 
dtypes: float64(1), int64(1), object(5)
memory usage: 1.6+ KB


## Labell Encoding

In [143]:
# List of categorical columns to encode
categorical_list = ['Website Domain', 'Found At', 'Categories', 'Investors', 'Source Urls']

# Apply Label Encoding to each categorical column
for col in categorical_list:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col]) # Now, 'col' will correctly iterate through individual column names.

In [144]:
df

Website Domain  Found At  Categories  Investors  Investors Count  \
0               18         0           1          0              1.0   
1               19        12           1          2              9.0   
2               19        21           1          0              1.0   
3                2         9           1         10              1.0   
4                8         3           1          3              1.0   
5               15         6           6          1              2.0   
6                3         4           0          9              1.0   
7                5        22           7          0              1.0   
8                0        18           1          5              1.0   
9                7         5           1          0              1.0   
10              11         1           3          0              1.0   
11               2        10           1         11              1.0   
12              16        20           3          0              1.0   
13              20        19           1          7              1.0   
14              14        13           1          0              1.0   
15               6        17           5          0              1.0   
16               1         7           1          0              1.0   
17               4         2           1         12              1.0   
18              10        14           1          0              1.0   
19              12         6           1          6              3.0   
20              17        15           3          0              1.0   
21               4        16           1          4              1.0   
22               1         8           3          0              1.0   
23               9        17           4          8              1.0   
24              13        11           2          0              1.0   
25              17        15           1          0              1.0   

    Amount Normalized  Source Urls  
0          1900000000           25  
1           522700000            5  
2            53671000           17  
3             8000000           16  
4             1960000           10  
5            27200000           20  
6            40000000           22  
7           685000000            3  
8            50000000            8  
9             6865000            9  
10            6700000           15  
11         2000000000           18  
12            4581000            6  
13          464695000            7  
14           10000000           13  
15           31000000           11  
16            5000000           23  
17           18139000            1  
18            1600000           21  
19           17400000            4  
20            1823000           14  
21           10000000           19  
22            3653000            0  
23           13200000            2  
24            2500000           12  
25            2500000           24